Traceback (most recent call last):
  File "/Users/fredericoteixeira/pyenv/rock-env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/fredericoteixeira/pyenv/rock-env/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/fredericoteixeira/pyenv/rock-env/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/fredericoteixeira/pyenv/rock-env/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/fredericoteixeira/pyenv/rock-env/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/fredericoteixeira/pyenv/rock-env/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/fredericoteixeira/pyenv/rock-env/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
par = PAR()
err_fd = np.zeros(len(par.ni))
err_fe = np.zeros(len(par.ni))

for n, ni in enumerate(par.ni):
    z = np.linspace(-par.zm, par.zm, ni)
    # semi-analytical solitary wave profile
    phi = SolitaryWaveGenerator(par.Ls, z, 0)
    # analytical compaction rate
    a_cmp = np.sign(z) * np.sqrt(-2. * par.V * (phi-1)**2 / phi**2 * (phi - (par.V-1.)/2.))
    # numerical compaction rate
    n_cmp_fd = SolveCompactionRateFiniteDifference(phi, z[1]-z[0])
    n_cmp_fe = SolveCompactionRateFiniteElement(phi, z[1]-z[0])
    # error
    err_fd[n] = np.linalg.norm(a_cmp-n_cmp_fd, 2) / np.linalg.norm(a_cmp, 2)
    err_fe[n] = np.linalg.norm(a_cmp-n_cmp_fe, 2) / np.linalg.norm(a_cmp, 2)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/4z/_rhsq3x965gc56klbm0nmv040000gn/T/ipykernel_24692/113554127.py[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;32mfor[0m [0mn[0m[0;34m,[0m [0mni[0m [0;32min[0m [0menumerate[0m[0;34m([0m[0mpar[0m[0;34m.[0m[0mni[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m     [0mz[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinspace[0m[0;34m([0m[0;34m-[0m[0mpar[0m[0;34m.[0m[0mzm[0m[0;34m,[0m [0mpar[0m[0;34m.[0m[0mzm[0m[0;34m,[0m [0mni[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m     [0;31m# semi-analytical solitary wave profile[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m     [0mphi[0m [0;34m=[0m [0mSolitaryWaveGenerator[0m[0;34m([0m[0mpar[0m[0;34m.[0m[0mLs[0m[0;34m,[0m [0mz[0m[0;34m,[0m [0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<__array_function__ internals>[0m in [0;36mlinspace[0;34m(*args, **kwargs)[0m

[0;32m~/pyenv/rock-env/lib/python3.9/site-packages/numpy/core/function_base.py[0m in [0;36mlinspace[0;34m(start, stop, num, endpoint, retstep, dtype, axis)[0m
[1;32m    118[0m [0;34m[0m[0m
[1;32m    119[0m     """
[0;32m--> 120[0;31m     [0mnum[0m [0;34m=[0m [0moperator[0m[0;34m.[0m[0mindex[0m[0;34m([0m[0mnum[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    121[0m     [0;32mif[0m [0mnum[0m [0;34m<[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    122[0m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Number of samples, %s, must be non-negative."[0m [0;34m%[0m [0mnum[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'numpy.float64' object cannot be interpreted as an integer
TypeError: 'numpy.float64' object cannot be interpreted as an integer

